import 'dotenv/config'
import express from 'express'
import cors from 'cors'
import rateLimit from 'express-rate-limit'
import multer from 'multer'
import bcrypt from 'bcryptjs'
import jwt from 'jsonwebtoken'
import crypto from 'node:crypto'
import { z } from 'zod'
import { initDb, id, now, one, many, run } from './db.js'
import { assessRisk } from './services/riskEngine.js'
import { areaSquareMeters, centroid, centroidDistanceMeters, normalizePolygon, polygonWithin } from './services/geo.js'

if (!process.env.JWT_SECRET || process.env.JWT_SECRET === 'replace-with-a-long-random-secret') throw new Error('Set a strong JWT_SECRET in backend/.env before starting the API.')
const app = express(), port = Number(process.env.PORT || 4000), aiUrl = (process.env.AI_SERVICE_URL || 'http://localhost:8000').replace(/\/$/, '')
app.use(cors({ origin: process.env.FRONTEND_ORIGIN?.split(',') || 'http://localhost:5174' }))
app.use(express.json({ limit: '1mb' })); app.use(rateLimit({ windowMs: 15 * 60_000, limit: 300, standardHeaders: true, legacyHeaders: false }))
app.use((req, res, next) => { req.requestId = crypto.randomUUID(); res.setHeader('x-request-id', req.requestId); next() })
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: Number(process.env.MAX_UPLOAD_BYTES || 10 * 1024 * 1024), files: 1 }, fileFilter: (_, f, cb) => cb(null, ['image/jpeg', 'image/png', 'image/webp'].includes(f.mimetype)) })
const fail = (res, status, code, message) => res.status(status).json({ error: { code, message, requestId: res.req.requestId } })
const parse = (schema, source, res) => { const result = schema.safeParse(source); if (!result.success) { fail(res, 422, 'VALIDATION_ERROR', result.error.issues.map(x => x.message).join('; ')); return null } return result.data }
const tokenFor = user => jwt.sign({ sub: user.id, role: user.role }, process.env.JWT_SECRET, { expiresIn: '8h', issuer: 'fasalyn' })
function auth(...roles) { return async (req, res, next) => { const raw = req.get('authorization')?.replace(/^Bearer /, ''); try { const claims = jwt.verify(raw, process.env.JWT_SECRET, { issuer: 'fasalyn' }); const user = await one('SELECT id,email,name,role FROM users WHERE id=?', [claims.sub]); if (!user) return fail(res, 401, 'UNAUTHENTICATED', 'Session is no longer valid.'); if (roles.length && !roles.includes(user.role)) return fail(res, 403, 'FORBIDDEN', 'You do not have permission for this operation.'); req.user = user; next() } catch { fail(res, 401, 'UNAUTHENTICATED', 'Sign in is required.') } } }
async function ownsPlot(userId, plotId) { return one('SELECT p.*,f.farmer_id,f.latitude,f.longitude FROM plots p JOIN farms f ON p.farm_id=f.id WHERE p.id=? AND f.farmer_id=?', [plotId, userId]) }
function farmOut(row) { if (!row) return null; return { ...row, polygon: row.polygon_geometry ? JSON.parse(row.polygon_geometry) : null, farmerId: row.farmer_id, areaSquareMeters: row.area_square_meters, areaUnit: row.area_unit, plantingDate: row.planting_date, growthStage: row.growth_stage, monitoringMode: row.monitoring_mode, createdAt: row.created_at, updatedAt: row.updated_at } }
function plotOut(row) { if (!row) return null; return { ...row, polygon: row.polygon_geometry ? JSON.parse(row.polygon_geometry) : null, farmId: row.farm_id, cropStage: row.crop_stage, areaSquareMeters: row.area_square_meters, areaUnit: row.area_unit, plantingDate: row.planting_date, createdAt: row.created_at, updatedAt: row.updated_at } }
function parseBoundary(value) { try { return normalizePolygon(value) } catch (error) { const next = new Error(error.message); next.status = 422; throw next } }
async function weatherFor(lat, lon) { if (!Number.isFinite(lat) || !Number.isFinite(lon)) return null; try { const r = await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${encodeURIComponent(lat)}&longitude=${encodeURIComponent(lon)}&current=temperature_2m,relative_humidity_2m,precipitation`, { signal: AbortSignal.timeout(6000) }); if (!r.ok) return null; const c = (await r.json()).current; return c && Number.isFinite(c.relative_humidity_2m) ? { provider: 'open-meteo', observedAt: c.time, temperature: c.temperature_2m, humidity: c.relative_humidity_2m, rainfall: c.precipitation } : null } catch { return null } }
async function riskForPlot(plot, detection = null, scanId = null) { const rows = await many('SELECT count FROM trap_observations WHERE plot_id=? ORDER BY observed_at DESC LIMIT 2', [plot.id]); const weather = await weatherFor(plot.latitude, plot.longitude); const risk = assessRisk({ detection, trapTrend: rows[0] ? { latest: rows[0].count, change: rows[1] ? rows[0].count - rows[1].count : 0 } : null, weather, cropStage: plot.crop_stage }); await run('INSERT INTO risk_assessments VALUES (?,?,?,?,?,?,?,?)', [id(), plot.id, scanId, risk.score, risk.level, JSON.stringify({ factors: risk.factors, missing: risk.missing, weather }), JSON.stringify(risk.forecast), now()]); return { ...risk, weather } }

app.get('/api/health', (_, res) => res.json({ status: 'ok', database: 'connected', aiService: aiUrl }))
app.get('/api/map/config', auth('FARMER','OFFICER','EXPERT','ADMIN'), (_, res) => res.json({ provider: process.env.MAP_PROVIDER || 'leaflet', standardTiles: process.env.MAP_STANDARD_TILES || 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', satelliteTiles: process.env.MAP_SATELLITE_TILES || 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', geocodingProvider: process.env.GEOCODING_PROVIDER || 'browser/manual', attribution: { standard: '© OpenStreetMap contributors', satellite: 'Tiles © Esri' } }))
app.post('/api/auth/register', async (req, res) => { const body = parse(z.object({ email: z.string().email(), password: z.string().min(12), name: z.string().min(2).max(80) }), req.body, res); if (!body) return; if (await one('SELECT id FROM users WHERE email=?', [body.email.toLowerCase()])) return fail(res, 409, 'EMAIL_EXISTS', 'An account with this email already exists.'); const user = { id: id(), email: body.email.toLowerCase(), name: body.name, role: 'FARMER' }; await run('INSERT INTO users VALUES (?,?,?,?,?,?)', [user.id, user.email, await bcrypt.hash(body.password, 12), user.name, user.role, now()]); res.status(201).json({ user, token: tokenFor(user) }) })
app.post('/api/auth/login', async (req, res) => { const body = parse(z.object({ email: z.string().email(), password: z.string().min(1) }), req.body, res); if (!body) return; const user = await one('SELECT * FROM users WHERE email=?', [body.email.toLowerCase()]); if (!user || !(await bcrypt.compare(body.password, user.password_hash))) return fail(res, 401, 'INVALID_CREDENTIALS', 'Email or password is incorrect.'); res.json({ user: { id: user.id, email: user.email, name: user.name, role: user.role }, token: tokenFor(user) }) })
app.post('/api/farms', auth('FARMER'), async (req, res) => { const body = parse(z.object({ id: z.string().uuid().optional(), name: z.string().min(2).max(100), latitude: z.number().min(-90).max(90).optional(), longitude: z.number().min(-180).max(180).optional(), polygonGeometry: z.any().optional(), crop: z.string().min(2).max(60).optional(), variety: z.string().max(80).optional(), plantingDate: z.string().max(30).optional(), growthStage: z.enum(['seedling','vegetative','flowering','fruiting','harvest']).optional(), monitoringMode: z.enum(['QUICK_DETECTION','SPATIAL']).optional() }), req.body, res); if (!body) return; let polygon = null, center = null, area = null; try { polygon = body.polygonGeometry ? parseBoundary(body.polygonGeometry) : null; center = polygon ? centroid(polygon) : null; area = polygon ? areaSquareMeters(polygon) : null } catch (error) { return fail(res, error.status || 422, 'INVALID_GEOMETRY', error.message) } const createdAt = now(); const farm = { id: body.id || id(), farmerId: req.user.id, name: body.name, latitude: center?.latitude ?? body.latitude ?? null, longitude: center?.longitude ?? body.longitude ?? null, polygon, areaSquareMeters: area, areaUnit: 'square metres', crop: body.crop || null, variety: body.variety || null, plantingDate: body.plantingDate || null, growthStage: body.growthStage || null, monitoringMode: body.monitoringMode || (polygon ? 'SPATIAL' : 'QUICK_DETECTION'), createdAt, updatedAt: createdAt }; await run('INSERT INTO farms (id,farmer_id,name,latitude,longitude,polygon_geometry,area_square_meters,area_unit,crop,variety,planting_date,growth_stage,monitoring_mode,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', [farm.id, farm.farmerId, farm.name, farm.latitude, farm.longitude, polygon ? JSON.stringify(polygon) : null, area, farm.areaUnit, farm.crop, farm.variety, farm.plantingDate, farm.growthStage, farm.monitoringMode, createdAt, createdAt]); res.status(201).json(farm) })
app.get('/api/farms', auth('FARMER'), async (req, res) => res.json((await many('SELECT * FROM farms WHERE farmer_id=? ORDER BY created_at DESC', [req.user.id])).map(farmOut)))
app.put('/api/farms/:farmId/boundary', auth('FARMER'), async (req, res) => { const farm = await one('SELECT * FROM farms WHERE id=? AND farmer_id=?', [req.params.farmId, req.user.id]); if (!farm) return fail(res, 404, 'NOT_FOUND', 'Farm not found.'); const body = parse(z.object({ polygonGeometry: z.any() }), req.body, res); if (!body) return; try { const polygon = parseBoundary(body.polygonGeometry), center = centroid(polygon), area = areaSquareMeters(polygon), updatedAt = now(); await run('UPDATE farms SET polygon_geometry=?,area_square_meters=?,latitude=?,longitude=?,monitoring_mode=?,updated_at=? WHERE id=?', [JSON.stringify(polygon), area, center.latitude, center.longitude, 'SPATIAL', updatedAt, farm.id]); res.json(farmOut(await one('SELECT * FROM farms WHERE id=?', [farm.id]))) } catch (error) { fail(res, error.status || 422, 'INVALID_GEOMETRY', error.message) } })
app.get('/api/farms/:farmId/plots', auth('FARMER'), async (req, res) => { const farm = await one('SELECT id FROM farms WHERE id=? AND farmer_id=?', [req.params.farmId, req.user.id]); if (!farm) return fail(res, 404, 'NOT_FOUND', 'Farm not found.'); res.json((await many('SELECT * FROM plots WHERE farm_id=? ORDER BY created_at DESC', [farm.id])).map(plotOut)) })
app.post('/api/farms/:farmId/plots', auth('FARMER'), async (req, res) => { const farm = await one('SELECT * FROM farms WHERE id=? AND farmer_id=?', [req.params.farmId, req.user.id]); if (!farm) return fail(res, 404, 'NOT_FOUND', 'Farm not found.'); const body = parse(z.object({ id: z.string().uuid().optional(), name: z.string().min(1).max(40), crop: z.string().min(2).max(60), cropStage: z.enum(['seedling','vegetative','flowering','fruiting','harvest']).optional(), polygonGeometry: z.any().optional(), variety: z.string().max(80).optional(), plantingDate: z.string().max(30).optional() }), req.body, res); if (!body) return; let polygon = null, area = null; try { polygon = body.polygonGeometry ? parseBoundary(body.polygonGeometry) : null; const farmPolygon = farm.polygon_geometry ? JSON.parse(farm.polygon_geometry) : null; if (polygon && farmPolygon && !polygonWithin(polygon, farmPolygon)) return fail(res, 422, 'PLOT_OUTSIDE_FARM', 'Plot boundary must stay inside the confirmed farm boundary.'); area = polygon ? areaSquareMeters(polygon) : null } catch (error) { return fail(res, error.status || 422, 'INVALID_GEOMETRY', error.message) } const createdAt = now(); const plot = { id: body.id || id(), farmId: farm.id, name: body.name, crop: body.crop, cropStage: body.cropStage || farm.growth_stage || null, polygon, areaSquareMeters: area, areaUnit: 'square metres', variety: body.variety || farm.variety || null, plantingDate: body.plantingDate || farm.planting_date || null, createdAt, updatedAt: createdAt }; await run('INSERT INTO plots (id,farm_id,name,crop,crop_stage,polygon_geometry,area_square_meters,area_unit,variety,planting_date,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)', [plot.id, plot.farmId, plot.name, plot.crop, plot.cropStage, polygon ? JSON.stringify(polygon) : null, area, plot.areaUnit, plot.variety, plot.plantingDate, createdAt, createdAt]); res.status(201).json(plot) })
app.get('/api/farms/:farmId/spatial-health', auth('FARMER','OFFICER','EXPERT','ADMIN'), async (req, res) => { const params = req.user.role === 'FARMER' ? [req.params.farmId, req.user.id] : [req.params.farmId]; const farm = await one(`SELECT * FROM farms WHERE id=? ${req.user.role === 'FARMER' ? 'AND farmer_id=?' : ''}`, params); if (!farm) return fail(res, 404, 'NOT_FOUND', 'Farm not found.'); const plots = await many('SELECT * FROM plots WHERE farm_id=? ORDER BY name', [farm.id]); const latestRisks = await Promise.all(plots.map(async plot => ({ plot, risk: await one('SELECT * FROM risk_assessments WHERE plot_id=? ORDER BY created_at DESC LIMIT 1', [plot.id]), traps: await many('SELECT * FROM trap_observations WHERE plot_id=? ORDER BY observed_at DESC LIMIT 5', [plot.id]) }))); const confirmed = latestRisks.filter(item => ['HIGH','CRITICAL'].includes(item.risk?.level) && item.plot.polygon_geometry).map(item => ({ ...item, polygon: JSON.parse(item.plot.polygon_geometry) })); res.json({ farm: farmOut(farm), plots: latestRisks.map(item => { const polygon = item.plot.polygon_geometry ? JSON.parse(item.plot.polygon_geometry) : null; const nearby = polygon ? confirmed.filter(source => source.plot.id !== item.plot.id).map(source => ({ plotId: source.plot.id, name: source.plot.name, distanceMeters: Math.round(centroidDistanceMeters(polygon, source.polygon) || 0), level: source.risk.level })).filter(source => source.distanceMeters <= 500) : []; return { ...plotOut(item.plot), latestRisk: item.risk ? { score: item.risk.score, level: item.risk.level, factors: JSON.parse(item.risk.factors_json), forecast: JSON.parse(item.risk.forecast_json), createdAt: item.risk.created_at } : null, trapObservations: item.traps, nearbyRisk: nearby } }) }) })
app.get('/api/plots/:plotId/risk', auth('FARMER'), async (req, res) => { const plot = await ownsPlot(req.user.id, req.params.plotId); if (!plot) return fail(res, 404, 'NOT_FOUND', 'Plot not found.'); const latest = await one('SELECT result_json,id FROM scans WHERE plot_id=? AND status=? ORDER BY created_at DESC LIMIT 1', [plot.id, 'COMPLETED']); const result = latest ? JSON.parse(latest.result_json) : null; res.json(await riskForPlot(plot, result?.prediction, latest?.id || null)) })
app.get('/api/weather', auth('FARMER'), async (req, res) => { const weather = await weatherFor(Number(req.query.latitude), Number(req.query.longitude)); if (!weather) return fail(res, 503, 'WEATHER_UNAVAILABLE', 'Weather data unavailable.'); res.json(weather) })
app.post('/api/traps/observations', auth('FARMER'), async (req, res) => { const body = parse(z.object({ plotId: z.string().uuid(), trapType: z.string().min(2).max(50), pest: z.string().min(2).max(80), count: z.number().int().min(0).max(100000), observedAt: z.string().datetime() }), req.body, res); if (!body) return; const plot = await ownsPlot(req.user.id, body.plotId); if (!plot) return fail(res, 404, 'NOT_FOUND', 'Plot not found.'); const observation = { id: id(), ...body, userId: req.user.id, createdAt: now() }; await run('INSERT INTO trap_observations VALUES (?,?,?,?,?,?,?,?)', [observation.id, body.plotId, req.user.id, body.trapType, body.pest, body.count, body.observedAt, observation.createdAt]); res.status(201).json({ observation, risk: await riskForPlot(plot) }) })
app.get('/api/plots/:plotId/traps', auth('FARMER'), async (req, res) => { const plot = await ownsPlot(req.user.id, req.params.plotId); if (!plot) return fail(res, 404, 'NOT_FOUND', 'Plot not found.'); res.json(await many('SELECT * FROM trap_observations WHERE plot_id=? ORDER BY observed_at DESC', [plot.id])) })
app.post('/api/scans', auth('FARMER'), upload.single('image'), async (req, res) => { if (!req.file) return fail(res, 400, 'IMAGE_REQUIRED', 'Upload a JPEG, PNG, or WebP image under the configured size limit.'); const plot = await ownsPlot(req.user.id, req.body.plotId); if (!plot) return fail(res, 404, 'NOT_FOUND', 'Plot not found.'); const scan = { id: id(), imageKey: `${id()}.${req.file.mimetype.split('/')[1]}`, createdAt: now() }; await run('INSERT INTO scans VALUES (?,?,?,?,?,?,?,?,?)', [scan.id, plot.id, req.user.id, scan.imageKey, req.file.mimetype, 'PROCESSING', null, null, scan.createdAt]); try { const response = await fetch(`${aiUrl}/infer`, { method: 'POST', headers: { 'content-type': req.file.mimetype, 'x-fasalyn-crop': plot.crop }, body: req.file.buffer, signal: AbortSignal.timeout(60_000) }); const inference = await response.json().catch(() => null); if (!response.ok) { await run('UPDATE scans SET status=? WHERE id=?', ['MODEL_UNAVAILABLE', scan.id]); return fail(res, response.status === 503 ? 503 : 502, 'MODEL_UNAVAILABLE', inference?.detail || 'Model inference is unavailable; no diagnosis was created.') }; await run('UPDATE scans SET status=?,model_id=?,result_json=? WHERE id=?', ['COMPLETED', inference.modelId, JSON.stringify(inference), scan.id]); const risk = await riskForPlot(plot, inference.prediction, scan.id); let officerReview = null; if (inference.prediction.confidence < Number(process.env.OFFICER_REVIEW_CONFIDENCE || .70) || inference.prediction.severity === 'high' || risk.level === 'HIGH') { officerReview = 'OFFICER_REVIEW'; await run('INSERT INTO officer_cases VALUES (?,?,?,?,?,?,?)', [id(), scan.id, officerReview, inference.prediction.severity, null, now(), now()]) }; res.status(201).json({ scan: { ...scan, status: 'COMPLETED' }, inference, risk, officerReview }) } catch { await run('UPDATE scans SET status=? WHERE id=?', ['MODEL_UNAVAILABLE', scan.id]); return fail(res, 503, 'MODEL_UNAVAILABLE', 'Model inference timed out or is unavailable; no diagnosis was created.') } })
app.get('/api/scans', auth('FARMER'), async (req, res) => res.json(await many('SELECT s.* FROM scans s JOIN plots p ON s.plot_id=p.id JOIN farms f ON p.farm_id=f.id WHERE f.farmer_id=? ORDER BY s.created_at DESC', [req.user.id])))
app.get('/api/officer/cases', auth('OFFICER','EXPERT','ADMIN'), async (_, res) => res.json(await many('SELECT c.*,s.result_json,p.name plot_name,p.crop,f.name farm_name FROM officer_cases c JOIN scans s ON c.scan_id=s.id JOIN plots p ON s.plot_id=p.id JOIN farms f ON p.farm_id=f.id ORDER BY c.updated_at DESC')))
app.get('/api/officer/farms', auth('OFFICER','EXPERT','ADMIN'), async (_, res) => { const rows = await many(`SELECT f.*,u.name farmer_name,(SELECT count(*) FROM plots p WHERE p.farm_id=f.id) plot_count,(SELECT count(*) FROM risk_assessments r JOIN plots p ON r.plot_id=p.id WHERE p.farm_id=f.id AND r.level IN ('HIGH','CRITICAL')) high_risk_records FROM farms f JOIN users u ON u.id=f.farmer_id ORDER BY f.updated_at DESC,f.created_at DESC`); res.json(rows.map(farmOut)) })
app.get('/api/officer/hotspots', auth('OFFICER','EXPERT','ADMIN'), async (_, res) => { const observations = await many(`SELECT t.pest,t.count,t.observed_at,p.name plot_name,p.polygon_geometry,f.id farm_id,f.name farm_name,f.latitude,f.longitude FROM trap_observations t JOIN plots p ON p.id=t.plot_id JOIN farms f ON f.id=p.farm_id ORDER BY t.observed_at DESC LIMIT 200`); const located = observations.map(row => { const polygon = row.polygon_geometry ? JSON.parse(row.polygon_geometry) : null; const center = polygon ? centroid(polygon) : { latitude: row.latitude, longitude: row.longitude }; return center?.latitude != null && center?.longitude != null ? { ...row, latitude: center.latitude, longitude: center.longitude } : null }).filter(Boolean); if (!located.length) return res.json({ status: 'INSUFFICIENT_DATA', message: 'No sufficient observations for hotspot analysis.', hotspots: [] }); res.json({ status: 'READY', hotspots: located }) })
app.post('/api/officer/cases/:caseId/reviews', auth('OFFICER','EXPERT','ADMIN'), async (req, res) => { const body = parse(z.object({ decision: z.enum(['OFFICER_CONFIRMED','EXPERT_REVIEW','EXPERT_CONFIRMED','REJECTED']), notes: z.string().max(2000).optional() }), req.body, res); if (!body) return; const c = await one('SELECT * FROM officer_cases WHERE id=?', [req.params.caseId]); if (!c) return fail(res, 404, 'NOT_FOUND', 'Case not found.'); if (body.decision.startsWith('EXPERT') && !['EXPERT','ADMIN'].includes(req.user.role)) return fail(res, 403, 'FORBIDDEN', 'Only an expert can make this decision.'); const review = { id: id(), caseId: c.id, reviewerId: req.user.id, ...body, createdAt: now() }; await run('INSERT INTO reviews VALUES (?,?,?,?,?,?)', [review.id, review.caseId, review.reviewerId, review.decision, review.notes || null, review.createdAt]); await run('UPDATE officer_cases SET status=?,assigned_to=?,updated_at=? WHERE id=?', [body.decision, req.user.id, now(), c.id]); res.status(201).json(review) })
app.get('/api/analytics/farmer', auth('FARMER'), async (req, res) => { const scans = await many(`SELECT substr(s.created_at,1,10) day, count(*) count FROM scans s JOIN plots p ON s.plot_id=p.id JOIN farms f ON p.farm_id=f.id WHERE f.farmer_id=? AND s.status='COMPLETED' GROUP BY day ORDER BY day`, [req.user.id]); const traps = await many(`SELECT substr(t.observed_at,1,10) day, sum(t.count) count FROM trap_observations t JOIN plots p ON t.plot_id=p.id JOIN farms f ON p.farm_id=f.id WHERE f.farmer_id=? GROUP BY day ORDER BY day`, [req.user.id]); res.json({ scans, traps }) })
app.get('/api/dashboard/farmer', auth('FARMER'), async (req,res)=>{const totals=await one(`SELECT (SELECT count(*) FROM scans s JOIN plots p ON s.plot_id=p.id JOIN farms f ON p.farm_id=f.id WHERE f.farmer_id=?) scans,(SELECT count(*) FROM trap_observations t JOIN plots p ON t.plot_id=p.id JOIN farms f ON p.farm_id=f.id WHERE f.farmer_id=?) traps,(SELECT count(*) FROM officer_cases c JOIN scans s ON c.scan_id=s.id JOIN plots p ON s.plot_id=p.id JOIN farms f ON p.farm_id=f.id WHERE f.farmer_id=? AND c.status NOT IN ('OFFICER_CONFIRMED','EXPERT_CONFIRMED','REJECTED')) openCases`,[req.user.id,req.user.id,req.user.id]);const plots=await many('SELECT p.* FROM plots p JOIN farms f ON p.farm_id=f.id WHERE f.farmer_id=? ORDER BY p.created_at DESC',[req.user.id]);res.json({totals,plots})})
app.use((err, req, res, _) => { if (err instanceof multer.MulterError) return fail(res, 400, 'UPLOAD_INVALID', err.code === 'LIMIT_FILE_SIZE' ? 'Image is too large.' : 'Invalid image upload.'); console.error(JSON.stringify({ requestId: req.requestId, error: err.message })); fail(res, 500, 'INTERNAL_ERROR', 'Unexpected server error.') })
await initDb(); app.listen(port, () => console.log(`Fasalyn API listening on :${port}`))
