import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ShieldCheck, Sprout } from 'lucide-react';
import { loginAccount, registerAccount } from '../services/api';
import { useAuthStore } from '../store/auth';
import { Button } from '../components/ui/Button';
import { Card, CardContent } from '../components/ui/Card';
const API = import.meta.env.VITE_API_URL || 'https://fasalyn-api.onrender.com/api';
type AccountRole = 'FARMER' | 'OFFICER';

export default function AuthPage() {
  const [mode, setMode] = useState<'login' | 'register'>('login');
  const [role, setRole] = useState<AccountRole>('FARMER');
  const [name, setName] = useState(''), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [officerCode, setOfficerCode] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const navigate = useNavigate(), login = useAuthStore((state) => state.login);
  const save = (result: any) => { login(result.user, result.token); navigate(result.user.role === 'OFFICER' ? '/officer' : '/', { replace: true }); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { save(mode === 'login' ? await loginAccount({ email, password }) : await registerAccount({ name, email, password, role, officerRegistrationCode: role === 'OFFICER' ? officerCode : undefined })); } catch (err: any) { setError(err.message || 'Unable to sign in.'); } finally { setBusy(false); } };
  const demo = async (demoRole: AccountRole = 'FARMER') => { setBusy(true); setError(''); try { const response = await fetch(`${API}/auth/demo`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ role: demoRole }) }); const result = await response.json(); if (!response.ok) throw new Error(result?.error?.message || 'Unable to start demo.'); save(result); } catch (err: any) { setError(err.message || 'Unable to start demo.'); } finally { setBusy(false); } };
  
  return <main className="min-h-screen overflow-y-auto bg-background p-4 sm:p-8"><div className="min-h-[calc(100vh-4rem)] grid place-items-center"><Card className="w-full max-w-md my-6"><CardContent className="p-6 sm:p-8"><div className="flex items-center gap-3 mb-6"><Sprout className="text-emeraldMain" /><div><h1 className="text-xl font-bold">Fasalyn</h1><p className="text-sm text-textSub">Farm intelligence and officer review</p></div></div><div className="flex gap-2 mb-4"><Button type="button" className="flex-1" variant={mode === 'login' ? 'primary' : 'ghost'} onClick={() => setMode('login')}>Sign in</Button><Button type="button" className="flex-1" variant={mode === 'register' ? 'primary' : 'ghost'} onClick={() => setMode('register')}>Create account</Button></div><div className="flex gap-2 mb-5"><Button type="button" size="sm" className="flex-1" variant={role === 'FARMER' ? 'secondary' : 'ghost'} onClick={() => setRole('FARMER')}>Farmer</Button><Button type="button" size="sm" className="flex-1" variant={role === 'OFFICER' ? 'secondary' : 'ghost'} onClick={() => setRole('OFFICER')}><ShieldCheck size={15} className="mr-1" />Officer</Button></div><form className="space-y-4" onSubmit={submit}>{mode === 'register' && <label className="block text-sm">Name<input className="mt-1 w-full rounded-lg border border-subtle bg-cardHover p-2" required value={name} onChange={(event) => setName(event.target.value)} /></label>}<label className="block text-sm">Email<input className="mt-1 w-full rounded-lg border border-subtle bg-cardHover p-2" required type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label className="block text-sm">Password<input className="mt-1 w-full rounded-lg border border-subtle bg-cardHover p-2" required minLength={mode === 'register' ? 12 : 1} type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label>{mode === 'register' && role === 'OFFICER' && <label className="block text-sm">Officer Registration Code<input className="mt-1 w-full rounded-lg border border-subtle bg-cardHover p-2" required value={officerCode} onChange={(event) => setOfficerCode(event.target.value)} /><p className="mt-1 text-xs text-emeraldMain font-medium">Use prototype code: OFFICER2026</p></label>}{error && <p role="alert" className="text-danger text-sm">{error}</p>}<Button className="w-full" type="submit" isLoading={busy}>{mode === 'login' ? `Sign in as ${role === 'OFFICER' ? 'Officer' : 'Farmer'}` : `Create ${role === 'OFFICER' ? 'Officer' : 'Farmer'} account`}</Button></form><div className="my-5 border-t border-subtle" /><div className="flex gap-2"><Button className="flex-1" variant="secondary" isLoading={busy} onClick={() => demo('FARMER')}>Farmer Demo</Button><Button className="flex-1" variant="secondary" isLoading={busy} onClick={() => demo('OFFICER')}>Officer Demo</Button></div></CardContent></Card></div></main>;
}
