import {Plus} from 'lucide-react'
import {useEffect,useState} from 'react'
import {PageTitle,Empty} from '../components/Shared'
import {getTraps,saveTrap} from '../services/api'
export default function Monitoring(){
 const plotId=localStorage.getItem('fasalyn-default-plot'),[count,setCount]=useState(''),[pest,setPest]=useState(''),[trapType,setTrapType]=useState('sticky trap'),[items,setItems]=useState([]),[state,setState]=useState(plotId?'loading':'missing'),[message,setMessage]=useState('')
 const load=async()=>{if(!plotId)return;try{setItems(await getTraps(plotId));setState('ready')}catch(e){setState('error');setMessage(e.message)}};useEffect(()=>{load()},[])
 const save=async e=>{e.preventDefault();setMessage('');try{const result=await saveTrap({plotId,trapType,pest,count:Number(count),observedAt:new Date().toISOString()});setItems(x=>[result.observation,...x]);setCount('');setPest('');setMessage('Observation saved and risk recalculated.')}catch(err){setMessage(err.message)}}
 if(!plotId)return <><PageTitle eyebrow="PEST MONITORING" title="Trap intelligence"/><Empty title="Create a farm and plot first" body="Pest observations are attached to a real plot."/></>
 return <><PageTitle eyebrow="PERSISTED FARM DATA" title="Trap intelligence"/><section className="monitor-grid"><article className="card active-trap"><p className="eyebrow">RECENT OBSERVATIONS</p>{state==='loading'&&<p>Loading observations…</p>}{state==='error'&&<p className="form-error">{message}</p>}{state==='ready'&&!items.length&&<Empty title="No trap observations yet" body="Record a field observation below."/>}{items.slice(0,8).map(x=><div className="timeline" key={x.id}><i/><div><b>{x.pest} · {x.count}</b><span>{x.trap_type||x.trapType}</span></div><small>{new Date(x.observed_at||x.observedAt).toLocaleDateString()}</small></div>)}</article><form className="card observation" onSubmit={save}><p className="eyebrow">ADD OBSERVATION</p><h2>Record trap count</h2><label>Trap type<input required value={trapType} onChange={e=>setTrapType(e.target.value)}/></label><label>Pest<input required value={pest} onChange={e=>setPest(e.target.value)} placeholder="e.g. Thrips"/></label><label>Count<input required type="number" min="0" value={count} onChange={e=>setCount(e.target.value)}/></label><button className="primary-action" type="submit"><Plus size={17}/> Save observation</button>{message&&<p className={message.includes('saved')?'form-success':'form-error'}>{message}</p>}</form></section></>}
