import {useEffect,useState} from 'react';import {PageTitle,Empty} from '../components/Shared';import {getOfficerCases,getOfficerFarms,getOfficerHotspots} from '../services/api'
const unavailable=(title,body)=><><PageTitle eyebrow="DATA-DRIVEN FEATURE" title={title}/><Empty title="Not available yet" body={body}/></>
export const Alerts=()=>unavailable('Alerts','Alerts will appear only after persisted risk, scan, or review events are implemented.')
export const Actions=()=>unavailable('Action plans','No data-backed action-plan workflow is configured yet.')
export const Assistant=()=>unavailable('Farm assistant','A grounded agricultural assistant service is not configured. No answer is generated.')
export const Knowledge=()=>unavailable('Knowledge center','No reviewed, versioned knowledge library is configured yet.')
export const MapPage=()=>unavailable('Disease map','No privacy-safe geographic case aggregation exists yet, so no markers are shown.')
export function Officer(){const[data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{Promise.all([getOfficerCases(),getOfficerFarms(),getOfficerHotspots()]).then(([cases,farms,hotspots])=>setData({cases,farms,hotspots})).catch(e=>setError(e.message))},[]);if(error)return <><PageTitle eyebrow="OFFICER REVIEW" title="Officer desk"/><Empty title="Officer access required" body={error}/></>;return <><PageTitle eyebrow="OFFICER REVIEW" title="Officer desk"/>{!data?<p>Loading officer data…</p>:<section className="officer-desk"><article className="card case-queue"><h2>Review cases</h2>{!data.cases.length?<Empty title="No review cases" body="Cases are created only from real scans meeting escalation criteria."/>:data.cases.map(c=>{const r=c.result_json?JSON.parse(c.result_json):null;return <div className="timeline" key={c.id}><i/><div><b>{c.farm_name} · {c.plot_name} · {c.crop}</b><span>{r?.prediction?.label||'No confirmed label'} · {r?Math.round(r.prediction.confidence*100)+'% model confidence':'No model result'} · {c.status}</span></div></div>})}</article><article className="card case-queue"><h2>Mapped farms</h2>{!data.farms.length?<Empty title="No mapped farms" body="Farm boundaries appear here after farmers confirm them."/>:data.farms.map(farm=><div className="timeline" key={farm.id}><i/><div><b>{farm.name}</b><span>{farm.polygon?'Boundary saved':'No boundary'} · {farm.plot_count} plots · {farm.high_risk_records} high-risk records</span></div></div>)}</article><article className="card case-queue"><h2>Anonymous hotspots</h2>{data.hotspots.status==='INSUFFICIENT_DATA'?<Empty title="No sufficient observations for hotspot analysis" body={data.hotspots.message}/>:data.hotspots.hotspots.slice(0,10).map(item=><div className="timeline" key={`${item.farm_id}-${item.observed_at}-${item.pest}`}><i/><div><b>{item.pest} · {item.count}</b><span>{item.farm_name} · {Number(item.latitude).toFixed(4)}, {Number(item.longitude).toFixed(4)}</span></div></div>)}</article></section>}</>}
export const Settings=()=>{const user=JSON.parse(localStorage.getItem('fasalyn-user')||'null');return <><PageTitle eyebrow="PREFERENCES" title="Settings"/><section className="card settings-card"><h2>{user?.name||'Not signed in'}</h2><p>{user?.role||'Use Setup or Sign in to access persisted farm data.'}</p><p>Offline trap observations are stored locally until successful synchronization. Images are not stored offline.</p></section></>}
