import { useEffect, useState } from 'react'
import { AlertTriangle, Bell, CloudSun, Droplets, Leaf, Menu, MoveRight, Signal, Wind, X } from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'
import { plots as demoPlots, forecast, advisory } from './data/demo'
import { getDemoFarm } from './services/api'
import FarmGrid from './components/FarmGrid'
import RiskRing from './components/RiskRing'
import Diagnosis from './components/Diagnosis'
import OfficerPanel from './components/OfficerPanel'

function App() {
 const [selected,setSelected]=useState('P5'), [window,setWindow]=useState('24h'), [online,setOnline]=useState(navigator.onLine), [menu,setMenu]=useState(false), [plots,setPlots]=useState(demoPlots)
 useEffect(()=>{const on=()=>setOnline(navigator.onLine);addEventListener('online',on);addEventListener('offline',on);return()=>{removeEventListener('online',on);removeEventListener('offline',on)}},[])
 useEffect(()=>{getDemoFarm().then(setPlots).catch(()=>{/* local demo data keeps the farm usable offline */})},[])
 const selectedPlot=plots.find(x=>x[0]===selected)
 return <main>
  <header><a className="brand"><Leaf fill="currentColor"/>Fasalyn</a><nav className={menu?'open':''}><a href="#farm">My farm</a><a href="#diagnosis">Diagnosis</a><a href="#officer">Officer portal</a></nav><div className="header-actions"><span className={`online ${online?'':'offline'}`}>{online?'Synced':'Offline queue'}</span><button className="icon"><Bell size={19}/></button><button className="icon mobile" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
  <section className="hero"><div><p className="eyebrow">SATURDAY, 13 SEPTEMBER</p><h1>Good morning, <i>Vishnu</i> <span>👋</span></h1><p className="lead">Your farm health is mostly stable today. One plot needs your attention.</p></div><div className="weather"><CloudSun/><div><b>28°C</b><span>Partly cloudy</span></div><div><Droplets size={16}/><span>67% humidity</span></div><div><Wind size={16}/><span>12 km/h</span></div></div></section>
  <section className="overview"><div className="health panel"><div><p className="eyebrow">DEMO CHILLI FARM</p><h2>Farm health</h2><p className="muted">Based on 9 active subplots</p></div><RiskRing/><div className="trend"><Signal size={18}/><span>+4 since last week</span></div></div><div className="attention panel"><div className="alert-icon"><AlertTriangle/></div><div><p className="eyebrow">ATTENTION REQUIRED</p><h2>High pest pressure in P5</h2><p>18 thrips detected in trap. Nearby plots may be at elevated risk.</p><button className="text-button" onClick={()=>document.querySelector('#farm').scrollIntoView({behavior:'smooth'})}>View risk <MoveRight size={17}/></button></div></div></section>
  <section id="farm" className="farm-section"><div className="section-heading"><div><p className="eyebrow">SPATIAL RISK INTELLIGENCE</p><h2>Your farm, plot by plot</h2><p className="muted">Tap a subplot to understand current pressure and predicted nearby risk.</p></div><div className="legend"><span className="dot stable"/>Stable <span className="dot moderate"/>Watch <span className="dot high"/>High</div></div><div className="farm-layout"><div className="farm-card panel"><div className="field-top"><span><Leaf size={16}/> Chilli · 2.4 acres</span><span>Last observation 18 min ago</span></div><FarmGrid plots={plots} selected={selected} onSelect={setSelected}/><div className="field-foot">P5’s elevated pressure is being assessed against weather, crop stage and surrounding plots.</div></div><motion.aside key={selected} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="plot-detail panel"><p className="eyebrow">SELECTED SUBPLOT</p><div className="detail-title"><h2>{selected}</h2><span className={`badge ${selectedPlot[1].toLowerCase()}`}>{selectedPlot[1]} risk</span></div><div className="metric"><b>{selected==='P5'?'18':'—'}</b><span>{selected==='P5'?'thrips in trap':'No latest trap reading'}</span></div><hr/><div className="detail-row"><span>Crop stage</span><b>Flowering</b></div><div className="detail-row"><span>AI confidence</span><b>{selected==='P5'?'91%':'—'}</b></div><button className="primary">Open plot record <MoveRight size={16}/></button></motion.aside></div></section>
  <section className="forecast panel"><div className="forecast-head"><div><p className="eyebrow">PEST RISK FORECAST</p><h2>Predicted elevated risk</h2></div><div className="tabs">{Object.keys(forecast).map(x=><button onClick={()=>setWindow(x)} className={window===x?'active':''} key={x}>{x}</button>)}</div></div><div className="forecast-row">{forecast[window].map(([id,status,value])=><div key={id} className="forecast-item"><span>{id}</span><b>{value}<small>/100</small></b><div className="bar"><i style={{width:`${value}%`}} className={status.toLowerCase()}/></div><em>{status}</em></div>)}</div><p className="forecast-note">Forecast uses current trap pressure, wind, humidity, crop stage and observed farm history. It indicates likelihood, not certainty.</p></section>
  <section className="advisory"><div><p className="eyebrow">EXPERT-REVIEWED ADVISORY</p><h2>Today’s practical actions</h2><p className="muted">A clear, low-risk plan for the P5 observation.</p></div><ol>{advisory.map((a,i)=><li key={a}><span>{String(i+1).padStart(2,'0')}</span>{a}</li>)}</ol></section>
  <section id="diagnosis"><Diagnosis/></section><section id="officer"><OfficerPanel/></section>
  <footer><a className="brand"><Leaf fill="currentColor"/>Fasalyn</a><span>Early detection. Practical decisions. Stronger farms.</span><span>SIH 2026 prototype</span></footer>
 </main>
}
export default App
